/*
 * generated by Xtext
 */
package org.xtext.project.tdsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class TransfoDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransformationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSrcModelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSrcModelSrcModelParserRuleCall_3_0 = (RuleCall)cSrcModelAssignment_3.eContents().get(0);
		private final Assignment cLayerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLayerLayerParserRuleCall_4_0 = (RuleCall)cLayerAssignment_4.eContents().get(0);
		private final Assignment cTargetModelAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTargetModelTrgModelParserRuleCall_5_0 = (RuleCall)cTargetModelAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Transformation:
		//	"transformation" name=ID "{" srcModel+=SrcModel layer+=Layer+ targetModel+=TrgModel "}";
		@Override public ParserRule getRule() { return rule; }

		//"transformation" name=ID "{" srcModel+=SrcModel layer+=Layer+ targetModel+=TrgModel "}"
		public Group getGroup() { return cGroup; }

		//"transformation"
		public Keyword getTransformationKeyword_0() { return cTransformationKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//srcModel+=SrcModel
		public Assignment getSrcModelAssignment_3() { return cSrcModelAssignment_3; }

		//SrcModel
		public RuleCall getSrcModelSrcModelParserRuleCall_3_0() { return cSrcModelSrcModelParserRuleCall_3_0; }

		//layer+=Layer+
		public Assignment getLayerAssignment_4() { return cLayerAssignment_4; }

		//Layer
		public RuleCall getLayerLayerParserRuleCall_4_0() { return cLayerLayerParserRuleCall_4_0; }

		//targetModel+=TrgModel
		public Assignment getTargetModelAssignment_5() { return cTargetModelAssignment_5; }

		//TrgModel
		public RuleCall getTargetModelTrgModelParserRuleCall_5_0() { return cTargetModelTrgModelParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class TrgModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TrgModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGenerateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cFilepathAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFilepathSTRINGTerminalRuleCall_2_0 = (RuleCall)cFilepathAssignment_2.eContents().get(0);
		
		//TrgModel:
		//	"Generate" name=ID filepath=STRING;
		@Override public ParserRule getRule() { return rule; }

		//"Generate" name=ID filepath=STRING
		public Group getGroup() { return cGroup; }

		//"Generate"
		public Keyword getGenerateKeyword_0() { return cGenerateKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//filepath=STRING
		public Assignment getFilepathAssignment_2() { return cFilepathAssignment_2; }

		//STRING
		public RuleCall getFilepathSTRINGTerminalRuleCall_2_0() { return cFilepathSTRINGTerminalRuleCall_2_0; }
	}

	public class SrcModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SrcModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cImportURIAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cImportURISTRINGTerminalRuleCall_2_0 = (RuleCall)cImportURIAssignment_2.eContents().get(0);
		
		//SrcModel:
		//	"Import" name=ID importURI=STRING;
		@Override public ParserRule getRule() { return rule; }

		//"Import" name=ID importURI=STRING
		public Group getGroup() { return cGroup; }

		//"Import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//importURI=STRING
		public Assignment getImportURIAssignment_2() { return cImportURIAssignment_2; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_2_0() { return cImportURISTRINGTerminalRuleCall_2_0; }
	}

	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		/// *Operation:
		//	'Rename' | 'Remove' | 'Add'
		//	
		//;
		//Rename:
		//	 (entity=[Import]'.')
		//	;
		//Remove:
		//	(entity=[Import])
		//;
		//Add:
		//	(entity=[Import])
		//;
		//
		//entity:
		//	'class' | 'Association' | 'Attribute'
		//;
		// * / / *Type:
		//  DataType | Entity;
		//DataType:
		//  "datatype" name=ID;
		//  
		//  Transformation:
		//  "transformation" name=ID "{"
		//    (layers+=Layer);  
		//    //source = sourcemodelref;
		//       
		//  "}";* / Layer:
		//	"apply" name=ID;
		@Override public ParserRule getRule() { return rule; }

		//"apply" name=ID
		public Group getGroup() { return cGroup; }

		//"apply"
		public Keyword getApplyKeyword_0() { return cApplyKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	
	
	private final TransformationElements pTransformation;
	private final TrgModelElements pTrgModel;
	private final SrcModelElements pSrcModel;
	private final LayerElements pLayer;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TransfoDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTransformation = new TransformationElements();
		this.pTrgModel = new TrgModelElements();
		this.pSrcModel = new SrcModelElements();
		this.pLayer = new LayerElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.project.tdsl.TransfoDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Transformation:
	//	"transformation" name=ID "{" srcModel+=SrcModel layer+=Layer+ targetModel+=TrgModel "}";
	public TransformationElements getTransformationAccess() {
		return pTransformation;
	}
	
	public ParserRule getTransformationRule() {
		return getTransformationAccess().getRule();
	}

	//TrgModel:
	//	"Generate" name=ID filepath=STRING;
	public TrgModelElements getTrgModelAccess() {
		return pTrgModel;
	}
	
	public ParserRule getTrgModelRule() {
		return getTrgModelAccess().getRule();
	}

	//SrcModel:
	//	"Import" name=ID importURI=STRING;
	public SrcModelElements getSrcModelAccess() {
		return pSrcModel;
	}
	
	public ParserRule getSrcModelRule() {
		return getSrcModelAccess().getRule();
	}

	/// *Operation:
	//	'Rename' | 'Remove' | 'Add'
	//	
	//;
	//Rename:
	//	 (entity=[Import]'.')
	//	;
	//Remove:
	//	(entity=[Import])
	//;
	//Add:
	//	(entity=[Import])
	//;
	//
	//entity:
	//	'class' | 'Association' | 'Attribute'
	//;
	// * / / *Type:
	//  DataType | Entity;
	//DataType:
	//  "datatype" name=ID;
	//  
	//  Transformation:
	//  "transformation" name=ID "{"
	//    (layers+=Layer);  
	//    //source = sourcemodelref;
	//       
	//  "}";* / Layer:
	//	"apply" name=ID;
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
