/*
 * generated by Xtext
 */
package org.xtext.project.tdsl.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.project.tdsl.services.TransfoDslGrammarAccess;
import org.xtext.project.tdsl.transfoDsl.Layer;
import org.xtext.project.tdsl.transfoDsl.SrcModel;
import org.xtext.project.tdsl.transfoDsl.TransfoDslPackage;
import org.xtext.project.tdsl.transfoDsl.Transformation;
import org.xtext.project.tdsl.transfoDsl.TrgModel;

@SuppressWarnings("all")
public class TransfoDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TransfoDslGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == TransfoDslPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case TransfoDslPackage.LAYER:
				sequence_Layer(context, (Layer) semanticObject); 
				return; 
			case TransfoDslPackage.SRC_MODEL:
				sequence_SrcModel(context, (SrcModel) semanticObject); 
				return; 
			case TransfoDslPackage.TRANSFORMATION:
				sequence_Transformation(context, (Transformation) semanticObject); 
				return; 
			case TransfoDslPackage.TRG_MODEL:
				sequence_TrgModel(context, (TrgModel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Layer(EObject context, Layer semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.LAYER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.LAYER__NAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getLayerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID importURI=STRING srcmetamodel=[EPackage|ID])
	 */
	protected void sequence_SrcModel(EObject context, SrcModel semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__NAME));
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__IMPORT_URI));
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__SRCMETAMODEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.SRC_MODEL__SRCMETAMODEL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getSrcModelAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSrcModelAccess().getImportURISTRINGTerminalRuleCall_2_0(), semanticObject.getImportURI());
		feeder.accept(grammarAccess.getSrcModelAccess().getSrcmetamodelEPackageIDTerminalRuleCall_3_1_0_1(), semanticObject.getSrcmetamodel());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID srcmodel+=SrcModel layer+=Layer+ targetmodel+=TrgModel)
	 */
	protected void sequence_Transformation(EObject context, Transformation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID filepath=STRING)
	 */
	protected void sequence_TrgModel(EObject context, TrgModel semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.TRG_MODEL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.TRG_MODEL__NAME));
			if(transientValues.isValueTransient(semanticObject, TransfoDslPackage.Literals.TRG_MODEL__FILEPATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TransfoDslPackage.Literals.TRG_MODEL__FILEPATH));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getTrgModelAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTrgModelAccess().getFilepathSTRINGTerminalRuleCall_2_0(), semanticObject.getFilepath());
		feeder.finish();
	}
}
