/*
 * generated by Xtext
 */
package org.xtext.project.tdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TransfoDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.project.tdsl.ui.internal.TransfoDslActivator.getInstance().getInjector("org.xtext.project.tdsl.TransfoDsl");
	}
	
}
