/*
 * generated by Xtext
 */
package org.xtext.project.tdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TransfoDslStandaloneSetup extends TransfoDslStandaloneSetupGenerated{

	public static void doSetup() {
		new TransfoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

