/*
 * generated by Xtext
 */
package org.xtext.project.tdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TransfoDslRuntimeModule extends org.xtext.project.tdsl.AbstractTransfoDslRuntimeModule {

}
