/*
 * generated by Xtext
 */
package org.xtext.project.tdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TransfoDslUiModule extends org.xtext.project.tdsl.ui.AbstractTransfoDslUiModule {
	public TransfoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
