/*
 * generated by Xtext
 */
package org.xtext.project.tdsl.ui.contentassist

import org.xtext.project.tdsl.ui.contentassist.AbstractTransfoDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TransfoDslProposalProvider extends AbstractTransfoDslProposalProvider {
}
