/**
 * generated by Xtext
 */
package org.xtext.project.tdsl.validation;

import org.xtext.project.tdsl.validation.AbstractTransfoDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TransfoDslValidator extends AbstractTransfoDslValidator {
}
