/*
 * generated by Xtext
 */
package org.xtext.project.tdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.project.tdsl.ui.internal.TransfoDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TransfoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TransfoDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TransfoDslActivator.getInstance().getInjector(TransfoDslActivator.ORG_XTEXT_PROJECT_TDSL_TRANSFODSL);
	}
	
}
